var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/admin/add/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0yg56uf._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0jk5ehi._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0kpj3~x.js")
R.c("server/chunks/ssr/[root-of-the-server]__0-rh4df._.js")
R.c("server/chunks/ssr/[root-of-the-server]__09z7o2x._.js")
R.c("server/chunks/ssr/_0vb2wy1._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/src_app_admin_layout_tsx_0at4vto._.js")
R.c("server/chunks/ssr/_next-internal_server_app_admin_add_page_actions_0fvvco0.js")
R.m(4234)
module.exports=R.m(4234).exports
