/**
 * Static food data — will be replaced by Supabase queries
 * This is a temporary data layer for Phase 1
 */

import type { Food } from '@/types/database'
import { generateSlug } from './slug'
import { supabase } from './supabase'

// Raw data — mapped to Food type
const RAW_FOODS: Omit<Food, 'id' | 'created_at' | 'updated_at' | 'slug' | 'created_by'>[] = [
  // === Original basics ===
  { name_th: "ไข่ ไก่ ทั้งใบ", name_en: "whole-egg", emoji: "🥚", calories: 72, protein: 6.3, fat: 4.8, carbs: 0.4, fiber: null, sodium: null, sugar: null, serving_size: "1 large (50g)", serving_weight_g: 50, category: "protein", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ไข่", "โปรตีน"] },
  { name_th: "ไข่ขาว", name_en: "egg-white", emoji: "🥚", calories: 17, protein: 3.6, fat: 0.1, carbs: 0.2, fiber: null, sodium: null, sugar: null, serving_size: "1 large (33g)", serving_weight_g: 33, category: "protein", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ไข่", "โปรตีน", "low-fat"] },
  { name_th: "ข้าวขาว (ข้าวสวย)", name_en: "white-rice", emoji: "🍚", calories: 130, protein: 2.7, fat: 0.3, carbs: 28.2, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "carb", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ข้าว", "คาร์บ"] },
  { name_th: "อกไก่ สุก เนื้อล้วน", name_en: "chicken-breast-cooked", emoji: "🍗", calories: 157, protein: 32.1, fat: 3.2, carbs: 0, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "protein", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ไก่", "โปรตีนสูง", "คลีน", "ลดน้ำหนัก"] },
  { name_th: "กล้วยหอม", name_en: "banana", emoji: "🍌", calories: 100, protein: 1.1, fat: 0.3, carbs: 23, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "fruit", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ผลไม้", "พลังงาน"] },
  { name_th: "โยเกิร์ตกรีก ไร้ไขมัน", name_en: "greek-yogurt-nonfat", emoji: "🍦", calories: 59, protein: 10.2, fat: 0.4, carbs: 3.6, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "dairy", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["นม", "โปรตีน", "low-fat"] },
  { name_th: "หมูสันใน", name_en: "pork-tenderloin", emoji: "🥩", calories: 187, protein: 30.4, fat: 6.3, carbs: 0, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "protein", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["หมู", "โปรตีนสูง"] },
  { name_th: "ผักบุ้ง", name_en: "morning-glory", emoji: "🥦", calories: 25, protein: 2.6, fat: 0.2, carbs: 3.1, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "vegetable", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ผัก", "low-cal"] },
  { name_th: "ข้าวกล้อง", name_en: "brown-rice", emoji: "🍚", calories: 111, protein: 2.6, fat: 0.9, carbs: 23, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "carb", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ข้าว", "คลีน", "ไฟเบอร์"] },
  { name_th: "บะหมี่กึ่งสำเร็จรูป", name_en: "instant-noodles", emoji: "🍜", calories: 255, protein: 6, fat: 11, carbs: 33, fiber: null, sodium: null, sugar: null, serving_size: "1 pack", serving_weight_g: 60, category: "main", subcategory: "mama", brand: "มาม่า", barcode: null, image_url: null, source: "manual", verified: true, tags: ["มาม่า", "บะหมี่", "กึ่งสำเร็จรูป"] },
  { name_th: "เนยถั่ว สกิปปี้", name_en: "peanut-butter-skippy", emoji: "🥜", calories: 196, protein: 7, fat: 16, carbs: 6, fiber: null, sodium: null, sugar: null, serving_size: "2 tbsp (32g)", serving_weight_g: 32, category: "fat", subcategory: null, brand: "Skippy", barcode: null, image_url: null, source: "manual", verified: true, tags: ["ถั่ว", "ไขมันดี"] },
  { name_th: "พิซซ่าฮัท เปปเปอโรนี่ แป้งหนา", name_en: "pizza-hut-pepperoni-thick", emoji: "🍕", calories: 329, protein: 13, fat: 14.8, carbs: 35.9, fiber: null, sodium: null, sugar: null, serving_size: "1 slice (113g)", serving_weight_g: 113, category: "main", subcategory: null, brand: "Pizza Hut", barcode: null, image_url: null, source: "manual", verified: true, tags: ["พิซซ่า", "ฟาสต์ฟู้ด"] },
  { name_th: "นมข้นหวาน", name_en: "sweetened-condensed-milk", emoji: "🥛", calories: 329, protein: 8, fat: 9, carbs: 54, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "dairy", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["นม", "หวาน"] },
  { name_th: "แครอท", name_en: "carrot", emoji: "🥕", calories: 46, protein: 0.9, fat: 0.2, carbs: 10, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "vegetable", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ผัก", "วิตามินเอ"] },
  { name_th: "Nutella", name_en: "nutella", emoji: "🍫", calories: 200, protein: 2, fat: 12, carbs: 21, fiber: null, sodium: null, sugar: null, serving_size: "2 tbsp (37g)", serving_weight_g: 37, category: "snack", subcategory: null, brand: "Nutella", barcode: null, image_url: null, source: "manual", verified: true, tags: ["ช็อกโกแลต", "ขนม", "spread"] },

  // === 7-Eleven ===
  { name_th: "ข้าวไก่ทอดไข่ดาว 7-Eleven", name_en: "7-eleven-chicken-rice-egg", emoji: "🍚", calories: 385, protein: 16, fat: 11, carbs: 52, fiber: null, sodium: 720, sugar: null, serving_size: "1 กล่อง (320g)", serving_weight_g: 320, category: "main", subcategory: "7-eleven", brand: "7-Eleven", barcode: null, image_url: null, source: "manual", verified: true, tags: ["7-eleven", "ข้าว", "ไก่"] },
  { name_th: "แซนด์วิชแฮมชีส 7-Eleven", name_en: "7-eleven-ham-cheese-sandwich", emoji: "🥪", calories: 280, protein: 11, fat: 9, carbs: 38, fiber: null, sodium: 580, sugar: null, serving_size: "1 ชิ้น (125g)", serving_weight_g: 125, category: "main", subcategory: "7-eleven", brand: "7-Eleven", barcode: null, image_url: null, source: "manual", verified: true, tags: ["7-eleven", "แซนด์วิช"] },
  { name_th: "ไส้กรอก 7-Eleven", name_en: "7-eleven-sausage", emoji: "🌭", calories: 210, protein: 12, fat: 14, carbs: 4, fiber: null, sodium: 650, sugar: null, serving_size: "1 ชิ้น (60g)", serving_weight_g: 60, category: "main", subcategory: "7-eleven", brand: "7-Eleven", barcode: null, image_url: null, source: "manual", verified: true, tags: ["7-eleven", "ไส้กรอก"] },
  { name_th: "ซาลาเปาหมูสับ 7-Eleven", name_en: "7-eleven-salapao", emoji: "🥟", calories: 180, protein: 8, fat: 6, carbs: 24, fiber: null, sodium: 420, sugar: null, serving_size: "1 ลูก (80g)", serving_weight_g: 80, category: "main", subcategory: "7-eleven", brand: "7-Eleven", barcode: null, image_url: null, source: "manual", verified: true, tags: ["7-eleven", "ซาลาเปา"] },
  { name_th: "โอนิกิริ 7-Eleven", name_en: "7-eleven-onigiri", emoji: "🍙", calories: 150, protein: 7, fat: 3, carbs: 26, fiber: null, sodium: 380, sugar: null, serving_size: "1 ลูก (100g)", serving_weight_g: 100, category: "main", subcategory: "7-eleven", brand: "7-Eleven", barcode: null, image_url: null, source: "manual", verified: true, tags: ["7-eleven", "โอนิกิริ", "ข้าว"] },
  { name_th: "ขนมปังชีส 7-Fresh", name_en: "7-fresh-cheese-bread", emoji: "🥐", calories: 260, protein: 9, fat: 12, carbs: 32, fiber: null, sodium: 450, sugar: null, serving_size: "1 ชิ้น (85g)", serving_weight_g: 85, category: "snack", subcategory: "7-eleven", brand: "7-Eleven", barcode: null, image_url: null, source: "manual", verified: true, tags: ["7-eleven", "ขนมปัง", "ชีส"] },

  // === อาหารไทยยอดนิยม ===
  { name_th: "ข้าวมันไก่", name_en: "hainanese-chicken-rice", emoji: "🍗", calories: 420, protein: 28, fat: 15, carbs: 46, fiber: null, sodium: 680, sugar: null, serving_size: "1 จาน (300g)", serving_weight_g: 300, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ข้าว", "ไก่", "อาหารไทย"] },
  { name_th: "ข้าวขาหมู", name_en: "pork-leg-rice", emoji: "🍖", calories: 480, protein: 22, fat: 18, carbs: 55, fiber: null, sodium: 920, sugar: null, serving_size: "1 จาน (320g)", serving_weight_g: 320, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ข้าว", "หมู", "อาหารไทย"] },
  { name_th: "ผัดไทย", name_en: "pad-thai", emoji: "🍝", calories: 380, protein: 14, fat: 16, carbs: 45, fiber: null, sodium: 850, sugar: 8, serving_size: "1 จาน (260g)", serving_weight_g: 260, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["บะหมี่", "อาหารไทย", "กุ้ง"] },
  { name_th: "ส้มตำ", name_en: "som-tam", emoji: "🥗", calories: 85, protein: 4, fat: 5, carbs: 8, fiber: 2, sodium: 420, sugar: 3, serving_size: "1 จาน (150g)", serving_weight_g: 150, category: "vegetable", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["สลัด", "อาหารไทย", "อีสาน", "low-cal"] },
  { name_th: "ต้มยำกุ้ง", name_en: "tom-yum-goong", emoji: "🍲", calories: 65, protein: 8, fat: 2, carbs: 6, fiber: 1, sodium: 580, sugar: 2, serving_size: "1 ชาม (250ml)", serving_weight_g: 250, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ซุป", "อาหารไทย", "กุ้ง", "low-cal"] },
  { name_th: "แกงเขียวหวาน", name_en: "green-curry", emoji: "🥘", calories: 320, protein: 18, fat: 18, carbs: 22, fiber: 2, sodium: 640, sugar: 6, serving_size: "1 ชาม (280g)", serving_weight_g: 280, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["แกง", "อาหารไทย", "กะทิ"] },
  { name_th: "ข้าวผัด", name_en: "fried-rice", emoji: "🍚", calories: 350, protein: 10, fat: 14, carbs: 46, fiber: null, sodium: 720, sugar: null, serving_size: "1 จาน (250g)", serving_weight_g: 250, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ข้าว", "อาหารไทย"] },
  { name_th: "กะเพราหมูสับไข่ดาว", name_en: "pad-krapao-moo-kai-dao", emoji: "🍳", calories: 550, protein: 28, fat: 22, carbs: 58, fiber: null, sodium: 800, sugar: null, serving_size: "1 จาน (350g)", serving_weight_g: 350, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["หมู", "กะเพรา", "ไข่ดาว", "อาหารไทย"] },
  { name_th: "ข้าวซอย", name_en: "khao-soi", emoji: "🍜", calories: 410, protein: 16, fat: 18, carbs: 48, fiber: null, sodium: 780, sugar: 4, serving_size: "1 ชาม (320g)", serving_weight_g: 320, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["บะหมี่", "อาหารไทย", "เหนือ"] },
  { name_th: "ก๋วยเตี๋ยวเรือ", name_en: "boat-noodles", emoji: "🍜", calories: 300, protein: 18, fat: 12, carbs: 32, fiber: null, sodium: 680, sugar: null, serving_size: "1 ชาม (250g)", serving_weight_g: 250, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ก๋วยเตี๋ยว", "อาหารไทย"] },
  { name_th: "ผัดกะเพราไก่", name_en: "pad-krapao-gai", emoji: "🍖", calories: 280, protein: 24, fat: 12, carbs: 18, fiber: null, sodium: 600, sugar: null, serving_size: "1 จาน (200g)", serving_weight_g: 200, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ไก่", "กะเพรา", "อาหารไทย"] },

  // === Fast food ===
  { name_th: "Big Mac McDonald's", name_en: "mcdonalds-big-mac", emoji: "🍔", calories: 553, protein: 26, fat: 30, carbs: 45, fiber: null, sodium: 1010, sugar: 8, serving_size: "1 ชิ้น (215g)", serving_weight_g: 215, category: "main", subcategory: null, brand: "McDonald's", barcode: null, image_url: null, source: "manual", verified: true, tags: ["burger", "ฟาสต์ฟู้ด"] },
  { name_th: "ไก่ทอด KFC ออริจินัล", name_en: "kfc-original-chicken", emoji: "🍗", calories: 320, protein: 28, fat: 17, carbs: 10, fiber: null, sodium: 640, sugar: null, serving_size: "1 ชิ้น (100g)", serving_weight_g: 100, category: "main", subcategory: null, brand: "KFC", barcode: null, image_url: null, source: "manual", verified: true, tags: ["ไก่", "ทอด", "ฟาสต์ฟู้ด"] },
  { name_th: "มาม่าต้มยำ", name_en: "mama-tom-yum", emoji: "🍜", calories: 280, protein: 9, fat: 12, carbs: 36, fiber: null, sodium: 1050, sugar: null, serving_size: "1 ซอง (60g)", serving_weight_g: 60, category: "main", subcategory: "mama", brand: "มาม่า", barcode: null, image_url: null, source: "manual", verified: true, tags: ["มาม่า", "บะหมี่", "ต้มยำ"] },

  // === เครื่องดื่ม ===
  { name_th: "ชาเขียวอิชิตัน", name_en: "ichitan-green-tea", emoji: "🍵", calories: 70, protein: 0, fat: 0, carbs: 17, fiber: null, sodium: 40, sugar: 16, serving_size: "1 ขวด (420ml)", serving_weight_g: 420, category: "drink", subcategory: null, brand: "อิชิตัน", barcode: null, image_url: null, source: "manual", verified: true, tags: ["ชา", "เขียว", "หวาน"] },
  { name_th: "โค้ก 330ml", name_en: "coca-cola-330ml", emoji: "🥤", calories: 139, protein: 0, fat: 0, carbs: 39, fiber: null, sodium: 40, sugar: 39, serving_size: "1 กระป๋อง (330ml)", serving_weight_g: 330, category: "drink", subcategory: null, brand: "Coca-Cola", barcode: null, image_url: null, source: "manual", verified: true, tags: ["น้ำอัดลม", "โค้ก", "หวาน"] },
  { name_th: "กาแฟลาเต้", name_en: "cafe-latte", emoji: "☕", calories: 150, protein: 8, fat: 6, carbs: 15, fiber: null, sodium: 120, sugar: 13, serving_size: "1 แก้ว (350ml)", serving_weight_g: 350, category: "drink", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["กาแฟ", "นม"] },
  { name_th: "นมจืด", name_en: "plain-milk", emoji: "🥛", calories: 150, protein: 8, fat: 8, carbs: 12, fiber: null, sodium: 120, sugar: 12, serving_size: "1 กล่อง (250ml)", serving_weight_g: 250, category: "dairy", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["นม", "แคลเซียม"] },
  { name_th: "น้ำส้มคั้น", name_en: "fresh-orange-juice", emoji: "🍊", calories: 112, protein: 1.7, fat: 0.5, carbs: 26, fiber: null, sodium: 5, sugar: 21, serving_size: "1 แก้ว (250ml)", serving_weight_g: 250, category: "drink", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["น้ำผลไม้", "ส้ม", "วิตามินซี"] },

  // === อาหารสุขภาพ ===
  { name_th: "อกไก่ย่าง", name_en: "grilled-chicken-breast", emoji: "🍗", calories: 165, protein: 34, fat: 3.6, carbs: 0, fiber: null, sodium: 60, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "protein", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ไก่", "โปรตีน", "คลีน", "ลดน้ำหนัก"] },
  { name_th: "สลัดผัก", name_en: "vegetable-salad", emoji: "🥗", calories: 65, protein: 3, fat: 4, carbs: 6, fiber: 2, sodium: 120, sugar: 2, serving_size: "1 จาน (150g)", serving_weight_g: 150, category: "vegetable", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["สลัด", "ผัก", "low-cal", "คลีน"] },
  { name_th: "เต้าหู้ขาว", name_en: "tofu", emoji: "⬜", calories: 76, protein: 8.1, fat: 4.8, carbs: 1.6, fiber: 0.4, sodium: 7, sugar: 0.4, serving_size: "100g", serving_weight_g: 100, category: "protein", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["เต้าหู้", "โปรตีน", "เวจ", "low-cal"] },
  { name_th: "ปลาแซลมอน", name_en: "salmon", emoji: "🐟", calories: 208, protein: 20, fat: 13, carbs: 0, fiber: null, sodium: 60, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "protein", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ปลา", "โปรตีน", "โอเมก้า-3", "คลีน"] },

  // === ขนม ===
  { name_th: "เลย์ คลาสสิค", name_en: "lays-classic", emoji: "🥔", calories: 161, protein: 2.2, fat: 10.1, carbs: 15, fiber: null, sodium: 281, sugar: null, serving_size: "1 ซอง (35g)", serving_weight_g: 35, category: "snack", subcategory: null, brand: "Lay's", barcode: null, image_url: null, source: "manual", verified: true, tags: ["มันฝรั่ง", "ขนม", "เค็ม"] },
  { name_th: "ทาโร่", name_en: "taro-snack", emoji: "🟣", calories: 154, protein: 1.8, fat: 9.2, carbs: 16, fiber: null, sodium: 250, sugar: null, serving_size: "1 ซอง (30g)", serving_weight_g: 30, category: "snack", subcategory: null, brand: "Taro", barcode: null, image_url: null, source: "manual", verified: true, tags: ["ขนม", "เค็ม"] },
  { name_th: "โปรตีนบาร์", name_en: "protein-bar", emoji: "📦", calories: 200, protein: 20, fat: 7, carbs: 15, fiber: 3, sodium: 120, sugar: 1, serving_size: "1 แท่ง (60g)", serving_weight_g: 60, category: "snack", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["โปรตีน", "คลีน", "อาหารเสริม"] },

  // === ผลไม้ ===
  { name_th: "มะม่วงสุก", name_en: "ripe-mango", emoji: "🥭", calories: 60, protein: 0.8, fat: 0.4, carbs: 15, fiber: 1.6, sodium: 1, sugar: 14, serving_size: "100g", serving_weight_g: 100, category: "fruit", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ผลไม้", "มะม่วง", "หวาน"] },
  { name_th: "แตงโม", name_en: "watermelon", emoji: "🍉", calories: 30, protein: 0.6, fat: 0.2, carbs: 8, fiber: 0.4, sodium: 1, sugar: 6, serving_size: "100g", serving_weight_g: 100, category: "fruit", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ผลไม้", "low-cal", "ฉ่ำ"] },
  { name_th: "ส้ม", name_en: "orange", emoji: "🍊", calories: 47, protein: 0.9, fat: 0.1, carbs: 12, fiber: 2.4, sodium: null, sugar: 9, serving_size: "100g", serving_weight_g: 100, category: "fruit", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ผลไม้", "วิตามินซี"] },

  // === Migrated from food_db.js ===
  { name_th: "ไข่, แดง", name_en: "ไข่-แดง", emoji: "🥚", calories: 55, protein: 2.7, fat: 4.5, carbs: 0.6, fiber: null, sodium: null, sugar: null, serving_size: "1 large(17 g)", serving_weight_g: 17, category: "protein", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ไข่", "โปรตีน"] },
  { name_th: "ขนมปัง, ฟาร์มเฮาส โรยัล", name_en: "ขนมปัง-ฟาร์มเฮาส-โรยัล", emoji: "🥛", calories: 139, protein: 5, fat: 3, carbs: 25, fiber: null, sodium: null, sugar: null, serving_size: "1 slice (55g)", serving_weight_g: 55, category: "dairy", subcategory: "farmhouse", brand: "Farmhouse", barcode: null, image_url: null, source: "manual", verified: true, tags: ["ขนม"] },
  { name_th: "ขนมปัง, ฟาร์มเฮาส", name_en: "ขนมปัง-ฟาร์มเฮาส", emoji: "🥛", calories: 65, protein: 2.5, fat: 1.3, carbs: 11, fiber: null, sodium: null, sugar: null, serving_size: "1 slice", serving_weight_g: null, category: "dairy", subcategory: "farmhouse", brand: "Farmhouse", barcode: null, image_url: null, source: "manual", verified: true, tags: ["ขนม"] },
  { name_th: "หมู, แฮม, แพตตี่(เบอร์เกอร์)", name_en: "หมู-แฮม-แพตตี่เบอร์เกอร์", emoji: "🥩", calories: 315, protein: 12.8, fat: 28.2, carbs: 1.7, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "protein", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["หมู", "โปรตีน"] },
  { name_th: "คอตเตจชีส", name_en: "คอตเตจชีส", emoji: "🧀", calories: 97, protein: 11, fat: 4.3, carbs: 3.4, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "dairy", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["dairy"] },
  { name_th: "ไก่, น่อง", name_en: "ไก่-น่อง", emoji: "🍗", calories: 153, protein: 18, fat: 9, carbs: 0, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "protein", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ไก่", "โปรตีน"] },
  { name_th: "ไก่, สะโพก", name_en: "ไก่-สะโพก", emoji: "🍗", calories: 218, protein: 16, fat: 17, carbs: 0.2, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "protein", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ไก่", "โปรตีน"] },
  { name_th: "ไก่, ปีก", name_en: "ไก่-ปีก", emoji: "🍗", calories: 79, protein: 7.5, fat: 5.4, carbs: 0, fiber: null, sodium: null, sugar: null, serving_size: "1 small", serving_weight_g: null, category: "protein", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ไก่", "โปรตีน"] },
  { name_th: "ขนม, ยูโร่เค๊ก", name_en: "ขนม-ยูโร่เค๊ก", emoji: "🥛", calories: 101, protein: 2, fat: 4.5, carbs: 13, fiber: null, sodium: null, sugar: null, serving_size: "1 pack (24 g)", serving_weight_g: 24, category: "dairy", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ขนม"] },
  { name_th: "เส็นเล็ก, มาม่า", name_en: "เส็นเล็ก-มาม่า", emoji: "🍽️", calories: 199, protein: 4, fat: 3, carbs: 39, fiber: null, sodium: null, sugar: null, serving_size: "1 pack (55 g)", serving_weight_g: 55, category: "main", subcategory: "mama", brand: "มาม่า", barcode: null, image_url: null, source: "manual", verified: true, tags: ["main"] },
  { name_th: "ซีเรียล, คอนเฟลก, เคลลอก", name_en: "ซีเรียล-คอนเฟลก-เคลลอก", emoji: "🍽️", calories: 365, protein: 7, fat: 0.8, carbs: 85, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: "Kellogg's", barcode: null, image_url: null, source: "manual", verified: true, tags: ["main"] },
  { name_th: "โยเกิร์ต, สตอเบอรี่, หนองโพ", name_en: "โยเกิร์ต-สตอเบอรี่-หนองโพ", emoji: "🍦", calories: 161, protein: 6, fat: 4.5, carbs: 24, fiber: null, sodium: null, sugar: null, serving_size: "1 cup (150 g)", serving_weight_g: 150, category: "dairy", subcategory: null, brand: "หนองโพ", barcode: null, image_url: null, source: "manual", verified: true, tags: ["dairy"] },
  { name_th: "กะหล่ำปลี", name_en: "กะหล่ำปลี", emoji: "🍽️", calories: 31, protein: 1.3, fat: 0.1, carbs: 6, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "vegetable", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ผัก"] },
  { name_th: "คะน้า", name_en: "คะน้า", emoji: "🍽️", calories: 22, protein: 1.1, fat: 0.7, carbs: 3.8, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "vegetable", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ผัก"] },
  { name_th: "ผัก, กวางตุั้ง", name_en: "ผัก-กวางตุั้ง", emoji: "🥦", calories: 20, protein: 2, fat: 0, carbs: 3, fiber: null, sodium: null, sugar: null, serving_size: "85g", serving_weight_g: 85, category: "vegetable", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ผัก"] },
  { name_th: "หมู, ลิ้น", name_en: "หมู-ลิ้น", emoji: "🥩", calories: 225, protein: 16.3, fat: 17.2, carbs: 0, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "protein", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["หมู", "โปรตีน"] },
  { name_th: "กระเทียม, สด", name_en: "กระเทียม-สด", emoji: "🍽️", calories: 5, protein: 0.2, fat: 0, carbs: 1, fiber: null, sodium: null, sugar: null, serving_size: "1 clove(3 g)", serving_weight_g: 3, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["เครื่องปรุง"] },
  { name_th: "ขิง", name_en: "ขิง", emoji: "🍽️", calories: 80, protein: 1.8, fat: 0.8, carbs: 17.8, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["เครื่องปรุง"] },
  { name_th: "ไก่, ตับ", name_en: "ไก่-ตับ", emoji: "🍗", calories: 163, protein: 26, fat: 6, carbs: 1.1, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "protein", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ไก่", "โปรตีน"] },
  { name_th: "ซอส, หอยนางรม (น้ำมันหอย)", name_en: "ซอส-หอยนางรม-น้ำมันหอย", emoji: "🍽️", calories: 9, protein: 0.2, fat: 0, carbs: 2, fiber: null, sodium: null, sugar: null, serving_size: "1 tbsp (18 g)", serving_weight_g: 18, category: "fat", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["น้ำมัน", "เครื่องปรุง"] },
  { name_th: "น้ำปลา", name_en: "น้ำปลา", emoji: "🐟", calories: 7, protein: 0.9, fat: 0, carbs: 0.7, fiber: null, sodium: null, sugar: null, serving_size: "1 tbsp (18 g)", serving_weight_g: 18, category: "protein", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ปลา", "เครื่องปรุง", "โปรตีน"] },
  { name_th: "ซีอิ๊ว, โชยุ", name_en: "ซีอิ๊ว-โชยุ", emoji: "🍽️", calories: 3, protein: 0.4, fat: 0, carbs: 0.3, fiber: null, sodium: null, sugar: null, serving_size: "1 tsp (5.3 g)", serving_weight_g: 3, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["เครื่องปรุง"] },
  { name_th: "หมู, สับ(บด), เนื้อ 72%", name_en: "หมู-สับบด-เนื้อ-72", emoji: "🥩", calories: 393, protein: 22.8, fat: 32.9, carbs: 1.4, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "protein", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["หมู", "โปรตีน"] },
  { name_th: "หมู, สับ(บด), เนื้อ 96%", name_en: "หมู-สับบด-เนื้อ-96", emoji: "🥩", calories: 185, protein: 31.7, fat: 6.2, carbs: 0.6, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "protein", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["หมู", "โปรตีน"] },
  { name_th: "น้ำตาล, ทรายขาว", name_en: "น้ำตาล-ทรายขาว", emoji: "🍽️", calories: 17, protein: 0, fat: 0, carbs: 4.2, fiber: null, sodium: null, sugar: null, serving_size: "1 tsp (4.2 g)", serving_weight_g: 2, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["เครื่องปรุง"] },
  { name_th: "ขนมปัง, โฮลหวีด, ฟาร์มเฮาส", name_en: "ขนมปัง-โฮลหวีด-ฟาร์มเฮาส", emoji: "🥛", calories: 130, protein: 6, fat: 2, carbs: 22, fiber: null, sodium: null, sugar: null, serving_size: "2 slices", serving_weight_g: null, category: "dairy", subcategory: "farmhouse", brand: "Farmhouse", barcode: null, image_url: null, source: "manual", verified: true, tags: ["ขนม"] },
  { name_th: "หมู, สัน (สีข้าง, ทั้งชิ้น)", name_en: "หมู-สัน-สีข้าง-ทั้งชิ้น", emoji: "🥩", calories: 198, protein: 19.7, fat: 12.6, carbs: 0, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "protein", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["หมู", "โปรตีน"] },
  { name_th: "ตะไคร้", name_en: "ตะไคร้", emoji: "🍽️", calories: 99, protein: 1.8, fat: 0.5, carbs: 25.3, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["main"] },
  { name_th: "ข่า", name_en: "ข่า", emoji: "🍽️", calories: 70, protein: 1.2, fat: 0.5, carbs: 15, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["main"] },
  { name_th: "กะทิ, ชาวเกาะ", name_en: "กะทิ-ชาวเกาะ", emoji: "🍽️", calories: 250, protein: 2.3, fat: 24, carbs: 6, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: "ชาวเกาะ", barcode: null, image_url: null, source: "manual", verified: true, tags: ["main"] },
  { name_th: "นมข้นจืด", name_en: "นมข้นจืด", emoji: "🥛", calories: 136, protein: 6.8, fat: 7.6, carbs: 10, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "dairy", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["dairy"] },
  { name_th: "พิซซ่าฮัท, 14นิ้ว, ซูเปอร์ซูพรีม", name_en: "พิซซ่าฮัท-14นิ้ว-ซูเปอร์ซูพรีม", emoji: "🍽️", calories: 305, protein: 14, fat: 13.5, carbs: 32, fiber: null, sodium: null, sugar: null, serving_size: "1 slice(123g)", serving_weight_g: 123, category: "main", subcategory: "pizza-hut", brand: "Pizza Hut", barcode: null, image_url: null, source: "manual", verified: true, tags: ["main"] },
  { name_th: "พริกไท, ดำ", name_en: "พริกไท-ดำ", emoji: "🍽️", calories: 326, protein: 10, fat: 3.3, carbs: 64, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["เครื่องปรุง"] },
  { name_th: "พริก, เขียว", name_en: "พริก-เขียว", emoji: "🍽️", calories: 40, protein: 2, fat: 0.2, carbs: 9.5, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["เครื่องปรุง"] },
  { name_th: "พริก, แดง", name_en: "พริก-แดง", emoji: "🍽️", calories: 40, protein: 1.9, fat: 0.4, carbs: 8.8, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["เครื่องปรุง"] },
  { name_th: "น้ำตาล, ทรายแดง", name_en: "น้ำตาล-ทรายแดง", emoji: "🍽️", calories: 18, protein: 0, fat: 0, carbs: 4.5, fiber: null, sodium: null, sugar: null, serving_size: "1 tsp (4.6g)", serving_weight_g: 6, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["เครื่องปรุง"] },
  { name_th: "เนย, จืด", name_en: "เนย-จืด", emoji: "🍽️", calories: 37, protein: 0, fat: 4.1, carbs: 0, fiber: null, sodium: null, sugar: null, serving_size: "1 pack (5g)", serving_weight_g: 5, category: "fat", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["fat"] },
  { name_th: "แตงกวา", name_en: "แตงกวา", emoji: "🍽️", calories: 18, protein: 0.6, fat: 0.1, carbs: 3.6, fiber: null, sodium: null, sugar: null, serving_size: "100 g", serving_weight_g: 100, category: "fruit", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["fruit"] },
  { name_th: "มะเขือม่วง", name_en: "มะเขือม่วง", emoji: "🍽️", calories: 30, protein: 1, fat: 0.2, carbs: 6, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["main"] },
  { name_th: "มะเขือเทศ", name_en: "มะเขือเทศ", emoji: "🍽️", calories: 18, protein: 1, fat: 0.1, carbs: 4, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["main"] },
  { name_th: "หัวหอม", name_en: "หัวหอม", emoji: "🍽️", calories: 40, protein: 1.1, fat: 0.1, carbs: 9.3, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["main"] },
  { name_th: "มันฝรั่ง", name_en: "มันฝรั่ง", emoji: "🍽️", calories: 77, protein: 2, fat: 0.1, carbs: 17, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "carb", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["carb"] },
  { name_th: "ขึ้นฉ่าย, ฝรั่ง", name_en: "ขึ้นฉ่าย-ฝรั่ง", emoji: "🍽️", calories: 17, protein: 0.7, fat: 0.2, carbs: 3, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["main"] },
  { name_th: "ผัก, หัวไชเท้า", name_en: "ผัก-หัวไชเท้า", emoji: "🥦", calories: 20, protein: 0.6, fat: 0.1, carbs: 4.1, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "vegetable", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ผัก"] },
  { name_th: "น้ำส้มสายชู", name_en: "น้ำส้มสายชู", emoji: "🍊", calories: 1, protein: 0, fat: 0, carbs: 0.1, fiber: null, sodium: null, sugar: null, serving_size: "1 tsp (5g)", serving_weight_g: 5, category: "fruit", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["fruit"] },
  { name_th: "หัวหอม, แดง (หอมแดง)", name_en: "หัวหอม-แดง-หอมแดง", emoji: "🍽️", calories: 72, protein: 2.5, fat: 0.1, carbs: 16.8, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["main"] },
  { name_th: "ผักชี", name_en: "ผักชี", emoji: "🥦", calories: 1, protein: 0.1, fat: 0, carbs: 0.1, fiber: null, sodium: null, sugar: null, serving_size: "0.25 cup(4g)", serving_weight_g: 4, category: "vegetable", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ผัก"] },
  { name_th: "แกงกะหรี่", name_en: "แกงกะหรี่", emoji: "🍽️", calories: 103, protein: 1, fat: 7, carbs: 9, fiber: null, sodium: null, sugar: null, serving_size: "1 cup (133g)", serving_weight_g: 133, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["แกง"] },
  { name_th: "ปลา, ทู", name_en: "ปลา-ทู", emoji: "🐟", calories: 152, protein: 20, fat: 7.9, carbs: 0, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "protein", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ปลา", "โปรตีน"] },
  { name_th: "ปลา, ทูน่า", name_en: "ปลา-ทูน่า", emoji: "🐟", calories: 138, protein: 23.3, fat: 4.9, carbs: 0, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "protein", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ปลา", "โปรตีน"] },
  { name_th: "ปลา,แซลมอน", name_en: "ปลาแซลมอน", emoji: "🐟", calories: 136, protein: 21.3, fat: 5.6, carbs: 0, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "protein", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ปลา", "โปรตีน"] },
  { name_th: "ปลา, ฮาลิบัด", name_en: "ปลา-ฮาลิบัด", emoji: "🐟", calories: 87, protein: 18.6, fat: 1.3, carbs: 0, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "protein", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ปลา", "โปรตีน"] },
  { name_th: "ปลา, นิล", name_en: "ปลา-นิล", emoji: "🐟", calories: 96, protein: 20.1, fat: 1.7, carbs: 0, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "protein", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ปลา", "โปรตีน"] },
  { name_th: "ขมิ้น", name_en: "ขมิ้น", emoji: "🍽️", calories: 9, protein: 0.2, fat: 0.2, carbs: 1.4, fiber: null, sodium: null, sugar: null, serving_size: "1 tsp (2.2 g)", serving_weight_g: 2, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["เครื่องปรุง"] },
  { name_th: "ยี่หร่า", name_en: "ยี่หร่า", emoji: "🍽️", calories: 10, protein: 0.4, fat: 0.5, carbs: 0.9, fiber: null, sodium: null, sugar: null, serving_size: "1 tsp (2.1 g)", serving_weight_g: 1, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["เครื่องปรุง"] },
  { name_th: "ผักชี, เมล็ด (ลูก)", name_en: "ผักชี-เมล็ด-ลูก", emoji: "🥦", calories: 8, protein: 0.2, fat: 0.3, carbs: 1, fiber: null, sodium: null, sugar: null, serving_size: "1 tsp (1.8g)", serving_weight_g: 8, category: "vegetable", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ผัก"] },
  { name_th: "หมู, สะเต๊ะ", name_en: "หมู-สะเต๊ะ", emoji: "🥩", calories: 347, protein: 36.6, fat: 16.5, carbs: 10.6, fiber: null, sodium: null, sugar: null, serving_size: "10 skewers", serving_weight_g: null, category: "protein", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["หมู", "โปรตีน"] },
  { name_th: "หมู, สันนอก, ไม่มัน", name_en: "หมู-สันนอก-ไม่มัน", emoji: "🥩", calories: 121, protein: 22.8, fat: 2.6, carbs: 0, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "protein", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["หมู", "โปรตีน"] },
  { name_th: "หมู, สันนอก, ส่วนหน้า", name_en: "หมู-สันนอก-ส่วนหน้า", emoji: "🥩", calories: 194, protein: 19.6, fat: 12.3, carbs: 0, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "protein", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["หมู", "โปรตีน"] },
  { name_th: "หมู, พอคชอบ", name_en: "หมู-พอคชอบ", emoji: "🥩", calories: 186, protein: 20.3, fat: 11, carbs: 0, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "protein", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["หมู", "โปรตีน"] },
  { name_th: "น้ำจิ้ม, อาจาด", name_en: "น้ำจิ้ม-อาจาด", emoji: "🍽️", calories: 96, protein: 1, fat: 0.2, carbs: 21.9, fiber: null, sodium: null, sugar: null, serving_size: "1 set (for 10 satay)", serving_weight_g: null, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["main"] },
  { name_th: "น้ำจิ้ม, สะเต๊ะ", name_en: "น้ำจิ้ม-สะเต๊ะ", emoji: "🍽️", calories: 259, protein: 8.6, fat: 22.3, carbs: 9.1, fiber: null, sodium: null, sugar: null, serving_size: "1 set (for 10 satay)", serving_weight_g: null, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["main"] },
  { name_th: "ถั่วลิสง, อบ, โก๋แก่", name_en: "ถั่วลิสง-อบ-โก๋แก่", emoji: "🥜", calories: 160, protein: 6, fat: 9, carbs: 14, fiber: null, sodium: null, sugar: null, serving_size: "30g", serving_weight_g: 30, category: "fat", subcategory: null, brand: "โก๋แก่", barcode: null, image_url: null, source: "manual", verified: true, tags: ["fat"] },
  { name_th: "ุถั่วลิสง, ดิบ", name_en: "ุถั่วลิสง-ดิบ", emoji: "🥜", calories: 567, protein: 25.8, fat: 49.2, carbs: 16.1, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "fat", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["fat"] },
  { name_th: "น้ำมันพืช, น้ำมันถั่วเหลือง", name_en: "น้ำมันพืช-น้ำมันถั่วเหลือง", emoji: "🥜", calories: 40, protein: 0, fat: 4.5, carbs: 0, fiber: null, sodium: null, sugar: null, serving_size: "1 tsp (4.5g)", serving_weight_g: 5, category: "fat", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["น้ำมัน"] },
  { name_th: "เนื้อปู", name_en: "เนื้อปู", emoji: "🍽️", calories: 83, protein: 17.9, fat: 0.7, carbs: 0, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "protein", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["โปรตีน"] },
  { name_th: "พริกไท", name_en: "พริกไท", emoji: "🍽️", calories: 296, protein: 10.4, fat: 2.1, carbs: 68.6, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["เครื่องปรุง"] },
  { name_th: "ข้าวผัด, ปู", name_en: "ข้าวผัด-ปู", emoji: "🍚", calories: 511, protein: 15.5, fat: 19.1, carbs: 68.8, fiber: null, sodium: null, sugar: null, serving_size: "1 dish", serving_weight_g: null, category: "carb", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ข้าว"] },
  { name_th: "แป้งสาลี, อเนกประสงค์", name_en: "แป้งสาลี-อเนกประสงค์", emoji: "🍽️", calories: 364, protein: 10.3, fat: 1, carbs: 76.3, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "carb", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["carb"] },
  { name_th: "แป้งสาลี, ขนมปัง", name_en: "แป้งสาลี-ขนมปัง", emoji: "🥛", calories: 361, protein: 12, fat: 1.7, carbs: 72.5, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "dairy", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ขนม"] },
  { name_th: "แป้งสาลี, เค็ก", name_en: "แป้งสาลี-เค็ก", emoji: "🍽️", calories: 362, protein: 8.2, fat: 0.9, carbs: 78, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "carb", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ขนม"] },
  { name_th: "น้ำตาล, ไอซิ่ง", name_en: "น้ำตาล-ไอซิ่ง", emoji: "🍽️", calories: 389, protein: 0, fat: 0, carbs: 99.8, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["เครื่องปรุง"] },
  { name_th: "ขนมเปี๊ยะ", name_en: "ขนมเปี๊ยะ", emoji: "🥛", calories: 115, protein: 2.2, fat: 5.4, carbs: 14.1, fiber: null, sodium: null, sugar: null, serving_size: "1 piece", serving_weight_g: null, category: "dairy", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ขนม"] },
  { name_th: "ไข่, แดง, เค็ม", name_en: "ไข่-แดง-เค็ม", emoji: "🥚", calories: 275, protein: 14.1, fat: 22.9, carbs: 1.8, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "protein", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ไข่", "โปรตีน"] },
  { name_th: "ข้าว, สาร", name_en: "ข้าว-สาร", emoji: "🍚", calories: 365, protein: 7.1, fat: 0.7, carbs: 80, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "carb", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ข้าว"] },
  { name_th: "ข้าว, หมกไก่", name_en: "ข้าว-หมกไก่", emoji: "🍚", calories: 905, protein: 55.7, fat: 38.4, carbs: 81.8, fiber: null, sodium: null, sugar: null, serving_size: "1 dish (for 1)", serving_weight_g: null, category: "protein", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ไก่", "ข้าว", "โปรตีน"] },
  { name_th: "อบเชิย", name_en: "อบเชิย", emoji: "🍽️", calories: 247, protein: 4, fat: 1.2, carbs: 80.6, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["เครื่องปรุง"] },
  { name_th: "ผงกะหรี่", name_en: "ผงกะหรี่", emoji: "🍽️", calories: 325, protein: 14.3, fat: 14, carbs: 55.8, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["แกง"] },
  { name_th: "ขนมปัง, เพิ่มวิตามิน, ฟาร์มเฮาส", name_en: "ขนมปัง-เพิ่มวิตามิน-ฟาร์มเฮาส", emoji: "🥛", calories: 130, protein: 5, fat: 2.5, carbs: 22, fiber: null, sodium: null, sugar: null, serving_size: "2 slices (43g)", serving_weight_g: 43, category: "dairy", subcategory: "farmhouse", brand: "Farmhouse", barcode: null, image_url: null, source: "manual", verified: true, tags: ["ขนม"] },
  { name_th: "แซนวิช, แฮม", name_en: "แซนวิช-แฮม", emoji: "🍽️", calories: 212, protein: 10.1, fat: 8.9, carbs: 22.6, fiber: null, sodium: null, sugar: null, serving_size: "1set", serving_weight_g: null, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["main"] },
  { name_th: "พิซซ่าฮัท, 12นิ้ว, ซูเปอร์ซูพรีม", name_en: "พิซซ่าฮัท-12นิ้ว-ซูเปอร์ซูพรีม", emoji: "🍽️", calories: 309, protein: 13.8, fat: 13.6, carbs: 32.5, fiber: null, sodium: null, sugar: null, serving_size: "1 slice (127g)", serving_weight_g: 127, category: "main", subcategory: "pizza-hut", brand: "Pizza Hut", barcode: null, image_url: null, source: "manual", verified: true, tags: ["main"] },
  { name_th: "มันฝรั่งทอด", name_en: "มันฝรั่งทอด", emoji: "🍽️", calories: 323, protein: 3.4, fat: 15.5, carbs: 42.6, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "carb", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ทอด"] },
  { name_th: "หมู, ทอด", name_en: "หมู-ทอด", emoji: "🥩", calories: 405, protein: 20.2, fat: 35.3, carbs: 0.8, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "protein", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["หมู", "ทอด", "โปรตีน"] },
  { name_th: "น้ำมัน, งา", name_en: "น้ำมัน-งา", emoji: "🍽️", calories: 40, protein: 0, fat: 4.5, carbs: 0, fiber: null, sodium: null, sugar: null, serving_size: "1 tsp (4.5g)", serving_weight_g: 5, category: "fat", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["น้ำมัน"] },
  { name_th: "ไอศกรีม, วานิลลา", name_en: "ไอศกรีม-วานิลลา", emoji: "🍽️", calories: 137, protein: 3.5, fat: 11, carbs: 23.6, fiber: null, sodium: null, sugar: null, serving_size: "1 scoop (100g)", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["main"] },
  { name_th: "ไอศกรีม, ช็อกโกแลต", name_en: "ไอศกรีม-ช็อกโกแลต", emoji: "🍽️", calories: 216, protein: 3.8, fat: 11, carbs: 28.2, fiber: null, sodium: null, sugar: null, serving_size: "1 scoop (100g)", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["main"] },
  { name_th: "ไอศกรีม, สตอเบอรี่", name_en: "ไอศกรีม-สตอเบอรี่", emoji: "🍽️", calories: 192, protein: 3.2, fat: 8.4, carbs: 27.6, fiber: null, sodium: null, sugar: null, serving_size: "1 scoop (100g)", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["main"] },
  { name_th: "น้ำสต๊อกไก่", name_en: "น้ำสต๊อกไก่", emoji: "🍗", calories: 6, protein: 0.6, fat: 0.2, carbs: 0.4, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "protein", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ไก่", "โปรตีน"] },
  { name_th: "ปลาหมึก", name_en: "ปลาหมึก", emoji: "🐟", calories: 92, protein: 15.6, fat: 1.4, carbs: 3.1, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "protein", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ปลา", "โปรตีน"] },
  { name_th: "วุ้นเส้น", name_en: "วุ้นเส้น", emoji: "🍽️", calories: 351, protein: 0.2, fat: 0.1, carbs: 86.1, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "carb", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["carb"] },
  { name_th: "กุนเชียง", name_en: "กุนเชียง", emoji: "🍽️", calories: 190, protein: 11, fat: 14, carbs: 6, fiber: null, sodium: null, sugar: null, serving_size: "1 link(46g)", serving_weight_g: 46, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["main"] },
  { name_th: "ไก่, เนื้อขาว, อบ", name_en: "ไก่-เนื้อขาว-อบ", emoji: "🍗", calories: 153, protein: 27.1, fat: 4.1, carbs: 0, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "protein", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ไก่", "โปรตีน"] },
  { name_th: "ไก่, อบ, น่อง,สะโพก", name_en: "ไก่-อบ-น่องสะโพก", emoji: "🍗", calories: 178, protein: 23.3, fat: 8.8, carbs: 0, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "protein", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ไก่", "โปรตีน"] },
  { name_th: "ผักกาดขาว", name_en: "ผักกาดขาว", emoji: "🥦", calories: 12, protein: 1.1, fat: 0.2, carbs: 2.2, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "vegetable", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ผัก"] },
  { name_th: "สุกี้น้ำ, ผัก", name_en: "สุกี้น้ำ-ผัก", emoji: "🥦", calories: 261, protein: 12, fat: 5.5, carbs: 41, fiber: null, sodium: null, sugar: null, serving_size: "1 bowl", serving_weight_g: null, category: "vegetable", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ผัก"] },
  { name_th: "ต้นหอม", name_en: "ต้นหอม", emoji: "🍽️", calories: 32, protein: 1.8, fat: 0.2, carbs: 7.3, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["main"] },
  { name_th: "Starbucks Refreshers Beverage, Strawberry Acai", name_en: "starbucks-refreshers-beverage-strawberry-acai", emoji: "🍽️", calories: 80, protein: 0, fat: 0, carbs: 18, fiber: null, sodium: null, sugar: null, serving_size: "Tall (12oz)", serving_weight_g: null, category: "main", subcategory: "starbucks", brand: "Starbucks", barcode: null, image_url: null, source: "manual", verified: true, tags: ["starbucks", "เครื่องดื่ม"] },
  { name_th: "Starbucks Refreshers Beverage, Cool Lime", name_en: "starbucks-refreshers-beverage-cool-lime", emoji: "🍽️", calories: 40, protein: 0, fat: 0, carbs: 10, fiber: null, sodium: null, sugar: null, serving_size: "Tall (12oz)", serving_weight_g: null, category: "main", subcategory: "starbucks", brand: "Starbucks", barcode: null, image_url: null, source: "manual", verified: true, tags: ["starbucks", "เครื่องดื่ม"] },
  { name_th: "Starbucks Refreshers Beverage, Very Berry Hibiscus", name_en: "starbucks-refreshers-beverage-very-berry-hibiscus", emoji: "🍽️", calories: 60, protein: 0, fat: 0, carbs: 14, fiber: null, sodium: null, sugar: null, serving_size: "Tall (12oz)", serving_weight_g: null, category: "main", subcategory: "starbucks", brand: "Starbucks", barcode: null, image_url: null, source: "manual", verified: true, tags: ["starbucks", "เครื่องดื่ม"] },
  { name_th: "โยเกิร์ต, ไร้ไขมัน, แอคทีเวีย", name_en: "โยเกิร์ต-ไร้ไขมัน-แอคทีเวีย", emoji: "🍦", calories: 60, protein: 3, fat: 0, carbs: 12, fiber: null, sodium: null, sugar: null, serving_size: "1 cup (105g)", serving_weight_g: 105, category: "dairy", subcategory: null, brand: "Activia", barcode: null, image_url: null, source: "manual", verified: true, tags: ["dairy"] },
  { name_th: "ขนม, โรเกอร์", name_en: "ขนม-โรเกอร์", emoji: "🥛", calories: 160, protein: 2, fat: 8, carbs: 20, fiber: null, sodium: null, sugar: null, serving_size: "9 pieces (32g)", serving_weight_g: 32, category: "dairy", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ขนม"] },
  { name_th: "หมู, กระดูกซี่โครง", name_en: "หมู-กระดูกซี่โครง", emoji: "🥩", calories: 397, protein: 29.1, fat: 30.3, carbs: 0, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "protein", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["หมู", "โปรตีน"] },
  { name_th: "ฟัก", name_en: "ฟัก", emoji: "🍽️", calories: 13, protein: 0.4, fat: 0.2, carbs: 3, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["main"] },
  { name_th: "แคนตาลูป", name_en: "แคนตาลูป", emoji: "🍽️", calories: 34, protein: 0.8, fat: 0.2, carbs: 8.2, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["main"] },
  { name_th: "ฮันนี่ดิว", name_en: "ฮันนี่ดิว", emoji: "🍽️", calories: 36, protein: 0.5, fat: 0.1, carbs: 9.1, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["main"] },
  { name_th: "มะละกอ", name_en: "มะละกอ", emoji: "🍽️", calories: 43, protein: 0.5, fat: 0.3, carbs: 10.8, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "fruit", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["fruit"] },
  { name_th: "ครีมชีส", name_en: "ครีมชีส", emoji: "🧀", calories: 342, protein: 5.9, fat: 34.2, carbs: 4.1, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "dairy", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["dairy"] },
  { name_th: "คอดเตจชีส, ไขมัน 2%", name_en: "คอดเตจชีส-ไขมัน-2", emoji: "🧀", calories: 81, protein: 10.5, fat: 2.3, carbs: 4.8, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "dairy", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["dairy"] },
  { name_th: "คอดเตจชีส, ไขมัน 1%", name_en: "คอดเตจชีส-ไขมัน-1", emoji: "🧀", calories: 72, protein: 12.4, fat: 1, carbs: 2.7, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "dairy", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["dairy"] },
  { name_th: "ครีม, ฮาฟแอนฮาฟ", name_en: "ครีม-ฮาฟแอนฮาฟ", emoji: "🍽️", calories: 130, protein: 3, fat: 11.5, carbs: 4.3, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "dairy", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["dairy"] },
  { name_th: "ครีม, ใส่กาแฟ", name_en: "ครีม-ใส่กาแฟ", emoji: "☕", calories: 195, protein: 2.7, fat: 19.3, carbs: 3.7, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "dairy", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["dairy"] },
  { name_th: "วิปครีม, ไลท์", name_en: "วิปครีม-ไลท์", emoji: "🍽️", calories: 292, protein: 2.2, fat: 30.9, carbs: 3, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "dairy", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["dairy"] },
  { name_th: "วิปครีม, เฮวี่", name_en: "วิปครีม-เฮวี่", emoji: "🍽️", calories: 345, protein: 2.1, fat: 37, carbs: 2.8, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "dairy", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["dairy"] },
  { name_th: "น้ำแกง, ซุบไก่", name_en: "น้ำแกง-ซุบไก่", emoji: "🍗", calories: 772, protein: 48.3, fat: 24.4, carbs: 93.6, fiber: null, sodium: null, sugar: null, serving_size: "1 bowl", serving_weight_g: null, category: "protein", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ไก่", "แกง", "โปรตีน"] },
  { name_th: "ผัด, ผักบุ้งไฟแดง", name_en: "ผัด-ผักบุ้งไฟแดง", emoji: "🥦", calories: 533, protein: 11.1, fat: 41.6, carbs: 31.1, fiber: null, sodium: null, sugar: null, serving_size: "1 dish", serving_weight_g: null, category: "vegetable", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ผัก"] },
  { name_th: "เต้าเจี่ยว", name_en: "เต้าเจี่ยว", emoji: "🍽️", calories: 719, protein: 0.9, fat: 80.5, carbs: 0.9, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["main"] },
  { name_th: "ข้าวราด, ผัดผักบุ้งไฟแดง", name_en: "ข้าวราด-ผัดผักบุ้งไฟแดง", emoji: "🍚", calories: 738, protein: 15.3, fat: 42.1, carbs: 75.6, fiber: null, sodium: null, sugar: null, serving_size: "1set", serving_weight_g: null, category: "vegetable", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ข้าว", "ผัก"] },
  { name_th: "ข้าวผัด, กุ้งแห้ง", name_en: "ข้าวผัด-กุ้งแห้ง", emoji: "🍚", calories: 827, protein: 33.2, fat: 33.8, carbs: 97.7, fiber: null, sodium: null, sugar: null, serving_size: "1set", serving_weight_g: null, category: "protein", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["กุ้ง", "ข้าว", "โปรตีน"] },
  { name_th: "ขนมปัง, โฮลหวีด, ฟาร์มเฮาส โรยัล", name_en: "ขนมปัง-โฮลหวีด-ฟาร์มเฮาส-โรยัล", emoji: "🥛", calories: 150, protein: 5, fat: 3, carbs: 26, fiber: null, sodium: null, sugar: null, serving_size: "1 slice (57g)", serving_weight_g: 57, category: "dairy", subcategory: "farmhouse", brand: "Farmhouse", barcode: null, image_url: null, source: "manual", verified: true, tags: ["ขนม"] },
  { name_th: "เต้าเจี้ยว, ละเอียด, UFC", name_en: "เต้าเจี้ยว-ละเอียด-ufc", emoji: "🍽️", calories: 15, protein: 1, fat: 0, carbs: 3, fiber: null, sodium: null, sugar: null, serving_size: "1 tbsp(17g)", serving_weight_g: 17, category: "main", subcategory: null, brand: "UFC", barcode: null, image_url: null, source: "manual", verified: true, tags: ["main"] },
  { name_th: "เต้าเจี้ยว, UFC", name_en: "เต้าเจี้ยว-ufc", emoji: "🍽️", calories: 20, protein: 1, fat: 0.5, carbs: 2, fiber: null, sodium: null, sugar: null, serving_size: "1 tbsp (15g)", serving_weight_g: 15, category: "main", subcategory: null, brand: "UFC", barcode: null, image_url: null, source: "manual", verified: true, tags: ["main"] },
  { name_th: "ถั่วฝักยาว", name_en: "ถั่วฝักยาว", emoji: "🥜", calories: 44, protein: 3.3, fat: 0.3, carbs: 9.5, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "fat", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["fat"] },
  { name_th: "กุ้งแห้ง", name_en: "กุ้งแห้ง", emoji: "🦐", calories: 253, protein: 51.7, fat: 3.4, carbs: 0, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "protein", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["กุ้ง", "โปรตีน"] },
  { name_th: "น้ำมัน, โอลีฟ", name_en: "น้ำมัน-โอลีฟ", emoji: "🍽️", calories: 884, protein: 0, fat: 100, carbs: 0, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "fat", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["น้ำมัน"] },
  { name_th: "ข้าวราด, หมูอบ", name_en: "ข้าวราด-หมูอบ", emoji: "🍚", calories: 972, protein: 56.9, fat: 33.7, carbs: 104.9, fiber: null, sodium: null, sugar: null, serving_size: "1 dish (for 1)", serving_weight_g: null, category: "protein", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["หมู", "ข้าว", "โปรตีน"] },
  { name_th: "ข้าวผัด, หมู", name_en: "ข้าวผัด-หมู", emoji: "🍚", calories: 627, protein: 54.7, fat: 37.2, carbs: 15, fiber: null, sodium: null, sugar: null, serving_size: "1set", serving_weight_g: null, category: "protein", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["หมู", "ข้าว", "โปรตีน"] },
  { name_th: "แกงจืด, หมู ไชเท้า", name_en: "แกงจืด-หมู-ไชเท้า", emoji: "🥩", calories: 981, protein: 72.8, fat: 63.9, carbs: 25.1, fiber: null, sodium: null, sugar: null, serving_size: "1 bowl", serving_weight_g: null, category: "protein", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["หมู", "แกง", "โปรตีน"] },
  { name_th: "หมู, ซุบก้อน, คะนอ", name_en: "หมู-ซุบก้อน-คะนอ", emoji: "🥩", calories: 20, protein: 1, fat: 1.5, carbs: 1, fiber: null, sodium: null, sugar: null, serving_size: "0.5 cube (6g)", serving_weight_g: 6, category: "protein", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["หมู", "โปรตีน"] },
  { name_th: "เห็ดหอม, เห็ดชิตาเกะ", name_en: "เห็ดหอม-เห็ดชิตาเกะ", emoji: "🍽️", calories: 34, protein: 2.2, fat: 0.5, carbs: 6.8, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["main"] },
  { name_th: "ข้าวผัด, กระเทียม เห็ดหอม", name_en: "ข้าวผัด-กระเทียม-เห็ดหอม", emoji: "🍚", calories: 645, protein: 9.7, fat: 28.1, carbs: 87.1, fiber: null, sodium: null, sugar: null, serving_size: "1set", serving_weight_g: null, category: "carb", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ข้าว", "เครื่องปรุง"] },
  { name_th: "เงาะกระป๋อง, มาลี", name_en: "เงาะกระป๋อง-มาลี", emoji: "🍽️", calories: 120, protein: 0, fat: 0, carbs: 30, fiber: null, sodium: null, sugar: null, serving_size: "5 pieces (140g)", serving_weight_g: 140, category: "fruit", subcategory: null, brand: "มาลี", barcode: null, image_url: null, source: "manual", verified: true, tags: ["fruit"] },
  { name_th: "ปลาแห้ง", name_en: "ปลาแห้ง", emoji: "🐟", calories: 116, protein: 23.5, fat: 1.7, carbs: 0, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "protein", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ปลา", "โปรตีน"] },
  { name_th: "ข้าวผัด, ปลาแห้ง", name_en: "ข้าวผัด-ปลาแห้ง", emoji: "🍚", calories: 669, protein: 25.2, fat: 29.1, carbs: 74.6, fiber: null, sodium: null, sugar: null, serving_size: "1set", serving_weight_g: null, category: "protein", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ปลา", "ข้าว", "โปรตีน"] },
  { name_th: "ปลา, เนื้อขาว", name_en: "ปลา-เนื้อขาว", emoji: "🐟", calories: 90, protein: 18.3, fat: 1.3, carbs: 0, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "protein", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ปลา", "โปรตีน"] },
  { name_th: "ปลา, อินทรี", name_en: "ปลา-อินทรี", emoji: "🐟", calories: 139, protein: 19.3, fat: 6.3, carbs: 0, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "protein", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ปลา", "โปรตีน"] },
  { name_th: "ปลาเค็ม", name_en: "ปลาเค็ม", emoji: "🐟", calories: 305, protein: 18.5, fat: 25.1, carbs: 0, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "protein", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ปลา", "โปรตีน"] },
  { name_th: "ข้าวผัด, ปลาเค็ม", name_en: "ข้าวผัด-ปลาเค็ม", emoji: "🍚", calories: 635, protein: 11, fat: 32.6, carbs: 73.4, fiber: null, sodium: null, sugar: null, serving_size: "1set", serving_weight_g: null, category: "protein", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ปลา", "ข้าว", "โปรตีน"] },
  { name_th: "หมู, หนัง", name_en: "หมู-หนัง", emoji: "🥩", calories: 415, protein: 21.8, fat: 35.7, carbs: 0, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "protein", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["หมู", "โปรตีน"] },
  { name_th: "แหนม, หมู", name_en: "แหนม-หมู", emoji: "🥩", calories: 200, protein: 11.5, fat: 16.5, carbs: 1.4, fiber: null, sodium: null, sugar: null, serving_size: "1 link (50g)", serving_weight_g: 50, category: "dairy", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["หมู"] },
  { name_th: "หมู, สะเต๊ะ, กับน้ำจิ้ม", name_en: "หมู-สะเต๊ะ-กับน้ำจิ้ม", emoji: "🥩", calories: 702, protein: 46.2, fat: 39, carbs: 41.5, fiber: null, sodium: null, sugar: null, serving_size: "1 set (10 skewers)", serving_weight_g: null, category: "protein", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["หมู", "โปรตีน"] },
  { name_th: "แกงจืด, หมู แตงกวา", name_en: "แกงจืด-หมู-แตงกวา", emoji: "🥩", calories: 415, protein: 54.7, fat: 18.7, carbs: 4.9, fiber: null, sodium: null, sugar: null, serving_size: "1 bowl", serving_weight_g: null, category: "fruit", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["หมู", "แกง"] },
  { name_th: "Abiyuch, raw", name_en: "abiyuch-raw", emoji: "🍽️", calories: 69, protein: 1.5, fat: 0.1, carbs: 17.6, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["main"] },
  { name_th: "Acerola, (west indian cherry), raw", name_en: "acerola-west-indian-cherry-raw", emoji: "🍽️", calories: 32, protein: 0.4, fat: 0.3, carbs: 7.7, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["main"] },
  { name_th: "Acorn stew (Apache)", name_en: "acorn-stew-apache", emoji: "🍽️", calories: 95, protein: 6.8, fat: 3.5, carbs: 9.2, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["main"] },
  { name_th: "Agave, cooked (Southwest)", name_en: "agave-cooked-southwest", emoji: "🍽️", calories: 135, protein: 1, fat: 0.3, carbs: 32, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["main"] },
  { name_th: "Agave, dried (Southwest)", name_en: "agave-dried-southwest", emoji: "🍽️", calories: 341, protein: 1.7, fat: 0.7, carbs: 82, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["main"] },
  { name_th: "Agave, raw (Southwest)", name_en: "agave-raw-southwest", emoji: "🍽️", calories: 68, protein: 0.5, fat: 0.2, carbs: 16.2, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["main"] },
  { name_th: "Agutuk, fish with shortening (Alaskan ice cream) (Alaska Native)", name_en: "agutuk-fish-with-shortening-alaskan-ice-cream-alas", emoji: "🍽️", calories: 470, protein: 9, fat: 43.5, carbs: 10.5, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["main"] },
  { name_th: "Agutuk, fish/berry with seal oil (Alaskan ice cream) (Alaska Native)", name_en: "agutuk-fishberry-with-seal-oil-alaskan-ice-cream-a", emoji: "🍽️", calories: 353, protein: 3.4, fat: 31.8, carbs: 13.4, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["main"] },
  { name_th: "Agutuk, meat-caribou (Alaskan ice cream) (Alaska Native)", name_en: "agutuk-meat-caribou-alaskan-ice-cream-alaska-nativ", emoji: "🍽️", calories: 258, protein: 21.7, fat: 18.6, carbs: 0.9, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["main"] },
  { name_th: "Alfalfa seeds, sprouted, raw", name_en: "alfalfa-seeds-sprouted-raw", emoji: "🍽️", calories: 23, protein: 4, fat: 0.7, carbs: 2.1, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["main"] },
  { name_th: "Amaranth grain, cooked", name_en: "amaranth-grain-cooked", emoji: "🍽️", calories: 102, protein: 3.8, fat: 1.6, carbs: 18.7, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["main"] },
  { name_th: "Amaranth grain, uncooked", name_en: "amaranth-grain-uncooked", emoji: "🍽️", calories: 371, protein: 13.6, fat: 7, carbs: 65.3, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["main"] },
  { name_th: "Amaranth leaves, cooked, boiled, drained, with salt", name_en: "amaranth-leaves-cooked-boiled-drained-with-salt", emoji: "🍽️", calories: 21, protein: 2.1, fat: 0.2, carbs: 4.1, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["main"] },
  { name_th: "Amaranth leaves, cooked, boiled, drained, without salt", name_en: "amaranth-leaves-cooked-boiled-drained-without-salt", emoji: "🍽️", calories: 21, protein: 2.1, fat: 0.2, carbs: 4.1, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["main"] },
  { name_th: "Amaranth leaves, raw", name_en: "amaranth-leaves-raw", emoji: "🍽️", calories: 23, protein: 2.5, fat: 0.3, carbs: 4, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["main"] },
  { name_th: "Animal fat, bacon grease", name_en: "animal-fat-bacon-grease", emoji: "🍽️", calories: 897, protein: 0, fat: 99.5, carbs: 0, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["main"] },
  { name_th: "APPLEBEE'S, 9 oz house sirloin steak", name_en: "applebees-9-oz-house-sirloin-steak", emoji: "🍽️", calories: 189, protein: 26.9, fat: 9.1, carbs: 0, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: "applebees", brand: "Applebee's", barcode: null, image_url: null, source: "manual", verified: true, tags: ["applebees", "ฟาสต์ฟู้ด"] },
  { name_th: "APPLEBEE'S, chicken tenders platter", name_en: "applebees-chicken-tenders-platter", emoji: "🍽️", calories: 297, protein: 19.6, fat: 16.2, carbs: 18, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: "applebees", brand: "Applebee's", barcode: null, image_url: null, source: "manual", verified: true, tags: ["applebees", "ฟาสต์ฟู้ด"] },
  { name_th: "APPLEBEE'S, chicken tenders, from kids' menu", name_en: "applebees-chicken-tenders-from-kids-menu", emoji: "🍽️", calories: 296, protein: 19.3, fat: 16.2, carbs: 18.4, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: "applebees", brand: "Applebee's", barcode: null, image_url: null, source: "manual", verified: true, tags: ["applebees", "ฟาสต์ฟู้ด"] },
  { name_th: "APPLEBEE'S, chili", name_en: "applebees-chili", emoji: "🍽️", calories: 157, protein: 12.6, fat: 9.8, carbs: 4.6, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: "applebees", brand: "Applebee's", barcode: null, image_url: null, source: "manual", verified: true, tags: ["applebees", "ฟาสต์ฟู้ด"] },
  { name_th: "APPLEBEE'S, coleslaw", name_en: "applebees-coleslaw", emoji: "🍽️", calories: 120, protein: 0.8, fat: 7.1, carbs: 13.2, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: "applebees", brand: "Applebee's", barcode: null, image_url: null, source: "manual", verified: true, tags: ["applebees", "ฟาสต์ฟู้ด"] },
  { name_th: "APPLEBEE'S, crunchy onion rings", name_en: "applebees-crunchy-onion-rings", emoji: "🍽️", calories: 356, protein: 4.6, fat: 19.6, carbs: 40.2, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: "applebees", brand: "Applebee's", barcode: null, image_url: null, source: "manual", verified: true, tags: ["applebees", "ฟาสต์ฟู้ด"] },
  { name_th: "APPLEBEE'S, Double Crunch Shrimp", name_en: "applebees-double-crunch-shrimp", emoji: "🍽️", calories: 323, protein: 12.3, fat: 18.9, carbs: 26, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: "applebees", brand: "Applebee's", barcode: null, image_url: null, source: "manual", verified: true, tags: ["applebees", "ฟาสต์ฟู้ด"] },
  { name_th: "APPLEBEE'S, fish, hand battered", name_en: "applebees-fish-hand-battered", emoji: "🍽️", calories: 202, protein: 13.2, fat: 9.1, carbs: 16.7, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: "applebees", brand: "Applebee's", barcode: null, image_url: null, source: "manual", verified: true, tags: ["applebees", "ฟาสต์ฟู้ด"] },
  { name_th: "APPLEBEE'S, french fries", name_en: "applebees-french-fries", emoji: "🍽️", calories: 290, protein: 3.3, fat: 13.2, carbs: 39.5, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: "applebees", brand: "Applebee's", barcode: null, image_url: null, source: "manual", verified: true, tags: ["applebees", "ฟาสต์ฟู้ด"] },
  { name_th: "APPLEBEE'S, KRAFT, Macaroni & Cheese, from kid's menu", name_en: "applebees-kraft-macaroni-cheese-from-kids-menu", emoji: "🍽️", calories: 143, protein: 5, fat: 4.3, carbs: 21.1, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: "applebees", brand: "Applebee's", barcode: null, image_url: null, source: "manual", verified: true, tags: ["applebees", "ฟาสต์ฟู้ด"] },
  { name_th: "APPLEBEE'S, mozzarella sticks", name_en: "applebees-mozzarella-sticks", emoji: "🍽️", calories: 316, protein: 14.9, fat: 18.4, carbs: 22.9, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: "applebees", brand: "Applebee's", barcode: null, image_url: null, source: "manual", verified: true, tags: ["applebees", "ฟาสต์ฟู้ด"] },
  { name_th: "Apples, canned, sweetened, sliced, drained, heated", name_en: "apples-canned-sweetened-sliced-drained-heated", emoji: "🍽️", calories: 67, protein: 0.2, fat: 0.4, carbs: 16.8, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["แอปเปิ้ล"] },
  { name_th: "Apples, canned, sweetened, sliced, drained, unheated", name_en: "apples-canned-sweetened-sliced-drained-unheated", emoji: "🍽️", calories: 67, protein: 0.2, fat: 0.5, carbs: 16.7, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["แอปเปิ้ล"] },
  { name_th: "Apples, dehydrated (low moisture), sulfured, stewed", name_en: "apples-dehydrated-low-moisture-sulfured-stewed", emoji: "🍽️", calories: 74, protein: 0.3, fat: 0.1, carbs: 19.9, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["แอปเปิ้ล"] },
  { name_th: "Apples, dehydrated (low moisture), sulfured, uncooked", name_en: "apples-dehydrated-low-moisture-sulfured-uncooked", emoji: "🍽️", calories: 346, protein: 1.3, fat: 0.6, carbs: 93.5, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["แอปเปิ้ล"] },
  { name_th: "Apples, dried, sulfured, stewed, with added sugar", name_en: "apples-dried-sulfured-stewed-with-added-sugar", emoji: "🍽️", calories: 83, protein: 0.2, fat: 0.1, carbs: 20.7, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["แอปเปิ้ล"] },
  { name_th: "Apples, dried, sulfured, stewed, without added sugar", name_en: "apples-dried-sulfured-stewed-without-added-sugar", emoji: "🍽️", calories: 57, protein: 0.2, fat: 0.1, carbs: 15.3, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["แอปเปิ้ล"] },
  { name_th: "Apples, dried, sulfured, uncooked", name_en: "apples-dried-sulfured-uncooked", emoji: "🍽️", calories: 243, protein: 0.9, fat: 0.3, carbs: 65.9, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["แอปเปิ้ล"] },
  { name_th: "Apples, frozen, unsweetened, heated", name_en: "apples-frozen-unsweetened-heated", emoji: "🍽️", calories: 47, protein: 0.3, fat: 0.3, carbs: 12, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["แอปเปิ้ล"] },
  { name_th: "Apples, frozen, unsweetened, unheated", name_en: "apples-frozen-unsweetened-unheated", emoji: "🍽️", calories: 48, protein: 0.3, fat: 0.3, carbs: 12.3, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["แอปเปิ้ล"] },
  { name_th: "แอปเปิ้ล, ฟูจิ", name_en: "แอปเปิ้ล-ฟูจิ", emoji: "🍎", calories: 63, protein: 0.2, fat: 0.2, carbs: 15.2, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "fruit", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ผลไม้", "แอปเปิ้ล"] },
  { name_th: "แอปเปิ้ล, กาล่า", name_en: "แอปเปิ้ล-กาล่า", emoji: "🍎", calories: 57, protein: 0.3, fat: 0.1, carbs: 13.7, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "fruit", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ผลไม้", "แอปเปิ้ล"] },
  { name_th: "Apples, raw, golden delicious, with skin", name_en: "apples-raw-golden-delicious-with-skin", emoji: "🍽️", calories: 57, protein: 0.3, fat: 0.2, carbs: 13.6, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["แอปเปิ้ล"] },
  { name_th: "Apples, raw, granny smith, with skin", name_en: "apples-raw-granny-smith-with-skin", emoji: "🍽️", calories: 58, protein: 0.4, fat: 0.2, carbs: 13.6, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["แอปเปิ้ล"] },
  { name_th: "Apples, raw, red delicious, with skin", name_en: "apples-raw-red-delicious-with-skin", emoji: "🍽️", calories: 59, protein: 0.3, fat: 0.2, carbs: 14.1, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["แอปเปิ้ล"] },
  { name_th: "แอปเปิ้ล", name_en: "แอปเปิ้ล", emoji: "🍎", calories: 52, protein: 0.3, fat: 0.2, carbs: 13.8, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "fruit", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ผลไม้", "แอปเปิ้ล"] },
  { name_th: "แอปเปิ้ล, ปอกเปลือก", name_en: "แอปเปิ้ล-ปอกเปลือก", emoji: "🍎", calories: 48, protein: 0.3, fat: 0.1, carbs: 12.8, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "fruit", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["ผลไม้", "แอปเปิ้ล"] },
  { name_th: "Apples, raw, without skin, cooked, boiled", name_en: "apples-raw-without-skin-cooked-boiled", emoji: "🍽️", calories: 53, protein: 0.3, fat: 0.4, carbs: 13.6, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["แอปเปิ้ล"] },
  { name_th: "Apples, raw, without skin, cooked, microwave", name_en: "apples-raw-without-skin-cooked-microwave", emoji: "🍽️", calories: 56, protein: 0.3, fat: 0.4, carbs: 14.4, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["แอปเปิ้ล"] },
  { name_th: "Applesauce, canned, sweetened, with salt", name_en: "applesauce-canned-sweetened-with-salt", emoji: "🍽️", calories: 76, protein: 0.2, fat: 0.2, carbs: 19.9, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["แอปเปิ้ล"] },
  { name_th: "Applesauce, canned, sweetened, without salt (includes USDA commodity)", name_en: "applesauce-canned-sweetened-without-salt-includes-", emoji: "🍽️", calories: 68, protein: 0.2, fat: 0.2, carbs: 17.5, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["แอปเปิ้ล"] },
  { name_th: "Applesauce, canned, unsweetened, with added ascorbic acid", name_en: "applesauce-canned-unsweetened-with-added-ascorbic-", emoji: "🍽️", calories: 42, protein: 0.2, fat: 0.1, carbs: 11.3, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["แอปเปิ้ล"] },
  { name_th: "Applesauce, canned, unsweetened, without added ascorbic acid (includes USDA commodity)", name_en: "applesauce-canned-unsweetened-without-added-ascorb", emoji: "🍽️", calories: 42, protein: 0.2, fat: 0.1, carbs: 11.3, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["แอปเปิ้ล"] },
  { name_th: "Apricot nectar, canned, with added ascorbic acid", name_en: "apricot-nectar-canned-with-added-ascorbic-acid", emoji: "🍽️", calories: 56, protein: 0.4, fat: 0.1, carbs: 14.4, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["main"] },
  { name_th: "Apricot nectar, canned, without added ascorbic acid", name_en: "apricot-nectar-canned-without-added-ascorbic-acid", emoji: "🍽️", calories: 56, protein: 0.4, fat: 0.1, carbs: 14.4, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["main"] },
  { name_th: "Apricots, canned, extra heavy syrup pack, without skin, solids and liquids", name_en: "apricots-canned-extra-heavy-syrup-pack-without-ski", emoji: "🍽️", calories: 96, protein: 0.6, fat: 0, carbs: 24.9, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["main"] },
  { name_th: "Apricots, canned, extra light syrup pack, with skin, solids and liquids", name_en: "apricots-canned-extra-light-syrup-pack-with-skin-s", emoji: "🍽️", calories: 49, protein: 0.6, fat: 0.1, carbs: 12.5, fiber: null, sodium: null, sugar: null, serving_size: "100g", serving_weight_g: 100, category: "main", subcategory: null, brand: null, barcode: null, image_url: null, source: "manual", verified: true, tags: ["main"] },
]

// Fallback static data (for when Supabase is unavailable)
const FALLBACK_FOODS: Food[] = RAW_FOODS.map((food, i) => ({
  ...food,
  id: `food-${i + 1}`,
  slug: food.name_en || generateSlug(food.name_th),
  created_by: null,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
}))

/**
 * Get all foods from Supabase
 * Falls back to static data if Supabase is unavailable
 */
export async function getAllFoods(): Promise<Food[]> {
  try {
    const allFoods: Food[] = []
    const pageSize = 1000
    let page = 0

    while (true) {
      const { data, error } = await supabase
        .from('foods')
        .select('*')
        .order('created_at', { ascending: false })
        .range(page * pageSize, (page + 1) * pageSize - 1)

      if (error) {
        console.error('Supabase error fetching foods:', error)
        return allFoods.length > 0 ? allFoods : FALLBACK_FOODS
      }

      if (!data || data.length === 0) break
      allFoods.push(...data)
      if (data.length < pageSize) break
      page++
    }

    return allFoods.length > 0 ? allFoods : FALLBACK_FOODS
  } catch (error) {
    console.error('Error fetching foods:', error)
    return FALLBACK_FOODS
  }
}

/**
 * Get a single food by slug
 * Falls back to static data if Supabase is unavailable
 */
export async function getFoodBySlug(slug: string): Promise<Food | null> {
  try {
    const { data, error } = await supabase
      .from('foods')
      .select('*')
      .eq('slug', slug)
      .single()

    if (error) {
      console.error(`Supabase error fetching food by slug ${slug}:`, error)
      return FALLBACK_FOODS.find(f => f.slug === slug) || null
    }

    return data || null
  } catch (error) {
    console.error(`Error fetching food by slug ${slug}:`, error)
    return FALLBACK_FOODS.find(f => f.slug === slug) || null
  }
}

/**
 * Get foods by category
 * Falls back to static data if Supabase is unavailable
 */
export async function getFoodsByCategory(category: string): Promise<Food[]> {
  try {
    const { data, error } = await supabase
      .from('foods')
      .select('*')
      .eq('category', category)
      .order('name_th', { ascending: true })
      .range(0, 4999)

    if (error) {
      console.error(`Supabase error fetching foods by category ${category}:`, error)
      return FALLBACK_FOODS.filter(f => f.category === category)
    }

    return data || []
  } catch (error) {
    console.error(`Error fetching foods by category ${category}:`, error)
    return FALLBACK_FOODS.filter(f => f.category === category)
  }
}

/**
 * Search foods by name, brand, or tags
 * Falls back to static data if Supabase is unavailable
 */
export async function searchFoods(query: string): Promise<Food[]> {
  if (!query || query.trim().length === 0) {
    return []
  }

  try {
    const { data, error } = await supabase
      .from('foods')
      .select('*')
      .or(
        `name_th.ilike.%${query}%,name_en.ilike.%${query}%,brand.ilike.%${query}%`
      )
      .order('name_th', { ascending: true })

    if (error) {
      console.error('Supabase error searching foods:', error)
      const q = query.toLowerCase()
      return FALLBACK_FOODS.filter(f =>
        f.name_th.toLowerCase().includes(q) ||
        (f.name_en && f.name_en.toLowerCase().includes(q)) ||
        (f.brand && f.brand.toLowerCase().includes(q)) ||
        (f.tags && f.tags.some(t => t.toLowerCase().includes(q)))
      )
    }

    return data || []
  } catch (error) {
    console.error('Error searching foods:', error)
    const q = query.toLowerCase()
    return FALLBACK_FOODS.filter(f =>
      f.name_th.toLowerCase().includes(q) ||
      (f.name_en && f.name_en.toLowerCase().includes(q)) ||
      (f.brand && f.brand.toLowerCase().includes(q)) ||
      (f.tags && f.tags.some(t => t.toLowerCase().includes(q)))
    )
  }
}

/**
 * Get related foods (same category, limit results)
 * Falls back to static data if Supabase is unavailable
 */
export async function getRelatedFoods(food: Food, limit = 5): Promise<Food[]> {
  try {
    const { data, error } = await supabase
      .from('foods')
      .select('*')
      .eq('category', food.category)
      .neq('id', food.id)
      .limit(limit)

    if (error) {
      console.error('Supabase error fetching related foods:', error)
      return FALLBACK_FOODS
        .filter(f => f.id !== food.id && f.category === food.category)
        .slice(0, limit)
    }

    return data || []
  } catch (error) {
    console.error('Error fetching related foods:', error)
    return FALLBACK_FOODS
      .filter(f => f.id !== food.id && f.category === food.category)
      .slice(0, limit)
  }
}
