var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/search/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__05_1wc6._.js")
R.c("server/chunks/ssr/src_lib_food-data_ts_07k~7cj._.js")
R.c("server/chunks/ssr/src_lib_supabase_ts_12ti~96._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0jk5ehi._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0lmppy_.js")
R.c("server/chunks/ssr/[root-of-the-server]__0-rh4df._.js")
R.c("server/chunks/ssr/[root-of-the-server]__09z7o2x._.js")
R.c("server/chunks/ssr/_0vb2wy1._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_search_page_actions_0koh-tf.js")
R.m(88736)
module.exports=R.m(88736).exports
