var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/admin/add/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0vgrx9k._.js")
R.c("server/chunks/ssr/04nh_next_dist_10r97vr._.js")
R.c("server/chunks/ssr/04nh_next_dist_esm_build_templates_app-page_0.35tcj.js")
R.c("server/chunks/ssr/[root-of-the-server]__11dk_lk._.js")
R.c("server/chunks/ssr/[root-of-the-server]__00aw5c3._.js")
R.c("server/chunks/ssr/mnt_Nutration website_calcheck_src_app_layout_tsx_0~mfj0h._.js")
R.c("server/chunks/ssr/04nh_next_dist_client_components_0ab9frc._.js")
R.c("server/chunks/ssr/04nh_next_dist_client_components_builtin_forbidden_06863t9.js")
R.c("server/chunks/ssr/04nh_next_dist_client_components_builtin_unauthorized_0b7wjba.js")
R.c("server/chunks/ssr/04nh_next_dist_client_components_builtin_global-error_0dwl67u.js")
R.c("server/chunks/ssr/mnt_Nutration website_calcheck_11au.28._.js")
R.c("server/chunks/ssr/0957_calcheck__next-internal_server_app_admin_add_page_actions_0z74pmq.js")
R.m(36675)
module.exports=R.m(36675).exports
